name: Test (Ubuntu)

on:
  push:
    branches:
      - main
      - ci
  pull_request:
    branches:
      - main
  schedule:
    - cron:  '0 0 * * 2'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version:
          - "3.10"
          - "3.11"
          - "3.12"
          - "3.13"
          - "3.14"

    env:
      DEPLOY_DOCS: ${{ github.ref == 'refs/heads/main' &&
                       matrix.python-version == '3.14' }}

    steps:
    - name: Install dependencies
      run: |
           sudo apt-get update -q
           sudo apt-get install -y gfortran libopenmpi-dev libboost-dev \
               libblas-dev liblapack-dev libfftw3-dev libgmp-dev libhdf5-dev \
               libscalapack-mpi-dev

    - name: Build & install SciFortran
      env:
        FC: mpifort
      run: |
           git clone https://github.com/SciFortran/SciFortran.git scifor.git
           mkdir scifor.build && pushd scifor.build
           cmake ../scifor.git -DCMAKE_BUILD_TYPE=Release
           make -j2
           make install
           popd

    - name: Build & install EDIpack
      env:
        FC: mpifort
      run: |
           git clone https://github.com/edipack/EDIpack EDIpack.git
           mkdir EDIpack.build && pushd EDIpack.build
           source $(readlink -f ${HOME}/opt/scifor/gnu/*/bin/scifor_config_user.sh)
           cmake ../EDIpack.git -DCMAKE_BUILD_TYPE=Release
           make -j2
           make install
           popd

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
           python -m pip install --upgrade pip
           pip install --user numpy scipy matplotlib mpi4py mako pytest networkx edipack2py

    - name: Build & install TRIQS
      env:
        CXX: g++
      run: |
           git clone https://github.com/TRIQS/triqs --branch 3.3.x triqs.git
           mkdir triqs.build && pushd triqs.build
           cmake ../triqs.git                                                  \
             -DCMAKE_BUILD_TYPE=Release                                        \
             -DCMAKE_INSTALL_PREFIX=${HOME}/opt/triqs                          \
             -DBuild_Tests=OFF
           make -j2
           make install
           popd

    - name: Checkout edipack2triqs
      uses: actions/checkout@v4

    - name: Test edipack2triqs
      run: |
           source $(readlink -f ${HOME}/opt/edipack/gnu/*/bin/edipack_config_user.sh)
           source ${HOME}/opt/triqs/share/triqs/triqsvars.sh
           py.test -v tests/

    - name: Install Sphinx and related packages
      if: env.DEPLOY_DOCS == 'true'
      run: >
           pip install
           sphinx sphinx-rtd-theme sphinxfortran-ng
           myst-parser nbsphinx linkify-it-py enum-tools[sphinx]

    - name: Build documentation
      if: env.DEPLOY_DOCS == 'true'
      run: |
           source ${HOME}/opt/triqs/share/triqs/triqsvars.sh
           sphinx-build -M html doc/ build/sphinx

    - name: Deploy documentation
      if: env.DEPLOY_DOCS == 'true'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        branch: gh-pages
        token: ${{ secrets.GITHUB_TOKEN }}
        folder: build/sphinx/html
